// app/layout.tsx
import PageHeader from './components/layout/PageHeader';
import './globals.css';
import { Providers } from './providers';

export const metadata = {
  title: 'My App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <PageHeader/>
          <div className='container m-auto'>
          {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
